#ifndef CSVFILEWRITER_GLOBAL_H
#define CSVFILEWRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CSVFILEWRITER_LIBRARY)
#  define CSVFILEWRITERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CSVFILEWRITERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CSVFILEWRITER_GLOBAL_H
